"""Franka server configuration constants."""

FRANKA_CMD_PORT = 5555
FRANKA_STATE_PORT = 5556
FRANKA_STREAM_PORT = 5557

STATE_HZ = 100
STREAM_HZ = 50

# Message types
MSG_JOINT_POSITION_CMD = 10
MSG_JOINT_VELOCITY_CMD = 11
MSG_CARTESIAN_POSE_CMD = 13
MSG_CARTESIAN_VELOCITY_CMD = 14
MSG_SET_CONTROL_MODE = 20
MSG_SET_GAINS = 21
MSG_STOP = 22
MSG_GET_STATE = 24
